### ISSUE TITLE
My head hurts?

### ISSUE THREAD

**Issue by antti-TIEA4** [APT-project/development_kit#1]
How to fix?

LLB version: f7456e7c431a32f5ee432972515b79e7abb0eadc
Node.js version: 6.6.0
Platform: Ubuntu 16.04

**Comment by Pikkuninja** [comment]
Sorry, can't fix :(

**Comment by antti-TIEA4** [comment]
Hmm.. I wonder why I''m not getting any notifications for comments?

**Comment by heinoapt** [comment]
Where should they go?

**Comment by antti-TIEA4** [comment]
The top right corner should have a notification box
![screenshot from 2016-09-21 19-26-31](https://cloud.githubusercontent.com/assets/22329344/18719755/5b0f1f64-8031-11e6-90bb-af1cd5c685cc.png)

**Comment by antti-TIEA4** [comment]
Got it: https://github.com/settings/notifications
I forgot they are not enabled by default.
